### ISSUE TITLE
Nav bar is not Sticky

### ISSUE THREAD

**Issue by PREM-A261** [Pallavi1926/Gym_Website__Using_HTML_CSS_JAVASCRIPT#2]
If your navigation bar (nav bar) is not "sticky," meaning it doesn't stay fixed at the top of the page when the user scrolls, it could be due to several potential issues. Here's a detailed explanation to help diagnose and fix the problem:

Sticky elements only work within the bounds of their scrolling container. If the container doesn’t have enough content to scroll, the sticky effect won’t activate because there’s no scroll event.

Solution: Ensure that the page or the container holding the nav bar has enough content so that scrolling can happen.

### **EXISTING VERSION**

![Screenshot 2024-10-01 173628](https://github.com/user-attachments/assets/bbdba83f-d505-43b6-aa6c-831fd07f26e9)

![Screenshot 2024-10-01 174237](https://github.com/user-attachments/assets/ef24042c-7efc-4975-bc9a-594ff839b56c)

### **UPDATED VERSION**

![Screenshot 2024-10-01 173705](https://github.com/user-attachments/assets/a7f7a8b0-7e62-482c-b84f-9d72be2c0587)

**Comment by PREM-A261** [comment]
Please Give me chance to resolve this problem

**Comment by vaibhav-soni74** [comment]
Being a front end developer i can solve this issue in no time, Can you please allow me to do the same?

**Comment by prvn-kumar01** [comment]
@Pallavi1926 I would like to fix this problem , Please assign it to me .

**Comment by dnyanesh99borse** [comment]
I believe i can solve this problem and can enhance it to 10x , requesting to please assign it to me

**Comment by Pallavi1926** [comment]
> Please Give me chance to resolve this problem

yes you can resolve it

**Comment by riyarane46** [comment]
I would really like to fix this issue if you would give me a chance to do so . GSSoC'24 Extd

**Comment by Ishajain0** [comment]
@Pallavi1926  please assign this task to me.
I would like to work on it...

**Comment by chmp0940** [comment]
I can fix this issue pls assign it to me !
