### ISSUE TITLE
Calculator Section Enhancement

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [Pallavi1926/Gym_Website__Using_HTML_CSS_JAVASCRIPT#224]
The Calculator Section is not user friendly . I will increase the input and output box area for clear visibility.
Also Utilizing the space between different types of calculator to create better user interaction.
![Screenshot 2024-10-06 024800](https://github.com/user-attachments/assets/ff266ab9-1f0a-4f06-b50c-84895ecbbc5b)
I will improve this part.
@Pallavi1926 please assign me this task under gssoc extended

**Comment by JOSHITHA6** [comment]
@Pallavi1926 please assign me this task under gssoc extended and hacktoberfest

**Comment by Adarsh-Chaubey03** [comment]
@Pallavi1926 please assign the task.

**Comment by Adarsh-Chaubey03** [comment]
@Pallavi1926 please review it
