### ISSUE TITLE
work on footer

### ISSUE THREAD

**Issue by Riyachauhan11** [Pallavi1926/Gym_Website__Using_HTML_CSS_JAVASCRIPT#305]
currently there's no footer on front page of website and the footer available in game modes is displaying 2023. I would like to add improvements to the project by adding the footer on front page and making the year it displays more dynamic as per the current year. Kindly assign me this issue

**Comment by harshg123g** [comment]
I would like to work on this project. Please assign to me.

**Comment by sanketdev1234** [comment]
I would like to work on this project. Please assign to me.
