### ISSUE TITLE
Add a Workout Session Page for Beginners

### ISSUE THREAD

**Issue by snehhhcodes** [Pallavi1926/Gym_Website__Using_HTML_CSS_JAVASCRIPT#309]
# Overview: 
I propose adding a new page to the project that will be dedicated to "Tutorial Workout Sessions" for beginners. This page will feature four distinct exercises, each with a picture, the name of the exercise, and its benefits. Below each exercise, there will be a clickable link that redirects users to a corresponding YouTube tutorial for step-by-step guidance. The page will be designed in a clean, simple layout with easy-to-access exercise details. Users will benefit from an organized structure where they can easily identify the exercise and understand its purpose. By clicking on the exercise, they will be taken directly to a tutorial video, removing the hassle of searching for appropriate content on their own.

This feature will simplify the process for beginners who often face difficulties in understanding how to start their workout routines. Users will find it easier to follow guided tutorials that explain proper exercise form and technique, significantly reducing the risk of injury. Furthermore, beginners can overcome their confusion and hesitation about workouts with clear, beginner-friendly instructions that are visually appealing and easy to access.

# Use case:

This feature will significantly raise engagement on the gym website by offering valuable, easy-to-follow workout content that encourages users to return frequently. Beginners, in particular, will feel more supported with clear exercise instructions and direct access to tutorial videos, which helps reduce confusion and build confidence. The seamless integration of exercise names, benefits, and clickable tutorials will keep users actively exploring the site, spending more time on it, and potentially sharing these resources with others.

Additionally, by providing high-quality, structured workout guidance, the website establishes itself as a helpful and reliable resource, increasing user retention and fostering a community of consistent visitors. This personalized learning approach will enhance user satisfaction, making them more likely to stay engaged and recommend the platform to others.

**Comment by snehhhcodes** [comment]
Hey @Pallavi1926 Please review this PR once and if suitable assign it to me under appropriate GSSOC and Hacktoberfest labels and level.

It would be great if you can assign this task to me for level3.
Thankyou!

**Comment by SaanyaGarg5** [comment]
You can assign me this task under gsssoc and hacktoberfest level 3 label.

**Comment by snehhhcodes** [comment]
@Pallavi1926 any update on this pallavi?
