### ISSUE TITLE
Adding hover effect to calculate BMI button in BMI calculator 

### ISSUE THREAD

**Issue by Lakde-Maheshwari** [Pallavi1926/Gym_Website__Using_HTML_CSS_JAVASCRIPT#346]
Problem : After we try to click on calculate BMI button there is no effect on color on hovering on it.

Impact : Users can experience more responsiveness as well as it will improve the visibility of the button.

**Comment by Lakde-Maheshwari** [comment]
I am willing to solve this issue Please assign me this issue.

**Comment by ambarmishraa** [comment]
Assign me this task, i will do it asap!
