### ISSUE TITLE
Auto-Scroll Not Working for Testimonials Section

### ISSUE THREAD

**Issue by TBorundia** [Pallavi1926/Gym_Website__Using_HTML_CSS_JAVASCRIPT#5]
![image](https://github.com/user-attachments/assets/7693fe63-d458-47e8-9423-3540cd1fe378)

The testimonials section currently displays one testimonial at a time, but it doesn't automatically scroll or rotate to show other feedback after a specific time interval. The goal is to implement an auto-scroll functionality to enhance user engagement.

**Comment by monishkumardvs** [comment]
Intresting one ..i can do it ..can u assign me

**Comment by sruthi070** [comment]
@TBorundia could you please assign this to me under Gssoc'24 Extd

**Comment by TBorundia** [comment]
@Pallavi1926 , this issue is raised by me . So it must be assgined to me as it is on the first come first serve basis.

**Comment by TBorundia** [comment]
@Pallavi1926 Mam, 
PR for this issue must be opened by me. Then how can be it assigned to others and also merged by other.

**Comment by Pallavi1926** [comment]
I have assigned this issue to you also. Please contribute to this.

**Comment by monishkumardvs** [comment]
can u add the labels
