### ISSUE TITLE
Inconsistent Form Background in Newsletter Section

### ISSUE THREAD

**Issue by PATILYASHH** [Pallavi1926/Gym_Website__Using_HTML_CSS_JAVASCRIPT#51]
**The newsletter form has a white background that clashes with the site's dark theme, creating a design inconsistency. The form's background needs to be adjusted to match the overall aesthetic for a more cohesive look.**

## screenshot 

![project3-before](https://github.com/user-attachments/assets/7bc72c66-ecdd-4a6c-bac9-d1234fdb7ad0)

**Comment by PATILYASHH** [comment]
please assign me this issue

**Comment by chetanck03** [comment]
I believe I can effectively resolve this issue and align the form's design with the rest of the site. Please assign me this task.

**Comment by PATILYASHH** [comment]
@poorvikaa08 I sent PR can you please check out it 
#52

**Comment by Gunpreet08** [comment]
hi @Pallavi1926 this issue is not yet resolved .please assign it to me

**Comment by PATILYASHH** [comment]
@Pallavi1926 sorry for being late but I just did PR on this issue can you please review my PR
