### ISSUE TITLE
Adding title and favicon

### ISSUE THREAD

**Issue by hetvipopat** [Pallavi1926/Gym_Website__Using_HTML_CSS_JAVASCRIPT#84]
Adding appropriate title and favicon

**Comment by sanikadesai76** [comment]
Hii @Pallavi1926, I am a contributor participating in the GirlScript Summer of Code 2024 - Extended Edition. I would like to express my interest in working on Issue #84.Could you please assign this issue to me?

**Comment by HafsaIffath** [comment]
Hi, I would like to work on this issue #84 please assign it to me
